import {Routes,Route} from 'react-router-dom'
import Navbar from './components/Navbar'
import Home from './pages/Home'
import Search from './pages/Search'
import MovieDetails from './pages/MovieDetails'
import Login from './pages/Login'
import Register from './pages/Register'
import Watchlist from './pages/Watchlist'
import Mood from './pages/Mood'
import NotFound from './pages/NotFound'
export default function App(){return <><Navbar/><main><Routes><Route path="/" element={<Home/>}/><Route path="/search" element={<Search/>}/><Route path="/movie/:id" element={<MovieDetails/>}/><Route path="/mood" element={<Mood/>}/><Route path="/watchlist" element={<Watchlist/>}/><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="*" element={<NotFound/>}/></Routes></main></>}
